name: ci
on:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: golangci-lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  lint-test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [windows-latest, macos-latest, ubuntu-latest]
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: go vet
        run: go vet ./...
      - name: go build
        run: go build
      - name: go test
        run: go test -v ./...